// bump-version.mjs 的纯函数测试。
//
// 为什么值得测：这些函数在正式打包流程里改写 package.json、Cargo.toml、
// Cargo.lock 与 tauri.conf.json。正则写错一个字符，最坏的情况不是报错，
// 而是"写成功但改了别的地方" —— 比如把某个依赖的 version 改掉。那种错要等到
// 编译或运行时才暴露，且看起来与版本号无关。所以这里逐个锁住命中位置。
//
// scripts/** 不在 tsconfig.app.json 的 include 里，也不在 eslint 的 files
// （只匹配 **/*.{ts,tsx}）里，vitest 是这些 .mjs 唯一的自动化闸门。

import { describe, expect, it } from "vitest";

import {
  bumpPatch,
  localDate,
  parseArgs,
  prependChangelogEntry,
  readCargoLockVersion,
  readCargoPackageVersion,
  replaceCargoLockVersion,
  replaceCargoPackageVersion,
  replaceJsonVersion,
} from "./bump-version.mjs";

describe("bumpPatch", () => {
  it("补丁号加一，主次版本号不动", () => {
    expect(bumpPatch("0.1.11")).toBe("0.1.12");
    expect(bumpPatch("1.4.0")).toBe("1.4.1");
  });

  it("补丁号跨十进位不退化成字符串拼接", () => {
    // "0.1.9" + 1 若按字符串处理会得到 0.1.91。
    expect(bumpPatch("0.1.9")).toBe("0.1.10");
    expect(bumpPatch("2.0.99")).toBe("2.0.100");
  });

  it("预发布标识与构建元数据一律拒绝，不猜该进哪一段", () => {
    expect(() => bumpPatch("0.1.12-rc.1")).toThrow(/三段纯数字/);
    expect(() => bumpPatch("0.1.12+build.5")).toThrow(/三段纯数字/);
    expect(() => bumpPatch("0.1")).toThrow(/三段纯数字/);
    expect(() => bumpPatch("v0.1.11")).toThrow(/三段纯数字/);
    expect(() => bumpPatch("")).toThrow(/三段纯数字/);
  });
});

describe("replaceJsonVersion", () => {
  const packageJson = [
    "{",
    '  "name": "provider-deck",',
    '  "private": true,',
    '  "version": "0.1.11",',
    '  "dependencies": {',
    '    "zod": "^4.1.0"',
    "  }",
    "}",
    "",
  ].join("\n");

  it("只改顶层 version，缩进与行尾原样保留", () => {
    const next = replaceJsonVersion(packageJson, "0.1.11", "0.1.12");
    expect(next).toContain('  "version": "0.1.12",');
    expect(next).toContain('    "zod": "^4.1.0"');
    expect(next.endsWith("}\n")).toBe(true);
    // 除版本号那一行，其余逐字不动。
    expect(next.split("\n").length).toBe(packageJson.split("\n").length);
  });

  it("依赖里有相同版本字符串时也不误伤", () => {
    const tricky = ['{', '  "version": "0.1.11",', '  "deps": {', '    "some-lib": "0.1.11"', "  }", "}", ""].join("\n");
    const next = replaceJsonVersion(tricky, "0.1.11", "0.1.12");
    expect(next).toContain('  "version": "0.1.12",');
    expect(next).toContain('    "some-lib": "0.1.11"');
  });

  it("找不到预期版本号时抛错，不静默返回原文", () => {
    expect(() => replaceJsonVersion(packageJson, "9.9.9", "9.9.10")).toThrow(/找不到值为/);
  });
});

describe("replaceCargoPackageVersion", () => {
  const cargoToml = [
    "[package]",
    'name = "provider-deck"',
    'version = "0.1.11"',
    'edition = "2021"',
    "",
    "[dependencies]",
    'serde = { version = "1.0", features = ["derive"] }',
    "",
    "[dependencies.tauri]",
    'version = "0.1.11"',
    "",
  ].join("\n");

  it("只改 [package] 段的 version", () => {
    const next = replaceCargoPackageVersion(cargoToml, "0.1.11", "0.1.12");
    const lines = next.split("\n");
    expect(lines[2]).toBe('version = "0.1.12"');
    // [dependencies.tauri] 段里同样的字符串必须保持原值。
    expect(lines[9]).toBe('version = "0.1.11"');
    expect(next).toContain('serde = { version = "1.0", features = ["derive"] }');
  });

  it("[package] 段版本与预期不符时抛错", () => {
    expect(() => replaceCargoPackageVersion(cargoToml, "0.2.0", "0.2.1")).toThrow(/与预期的/);
  });

  it("没有 [package] 段的 version 时抛错", () => {
    const noVersion = ["[package]", 'name = "provider-deck"', "", "[dependencies]", ""].join("\n");
    expect(() => replaceCargoPackageVersion(noVersion, "0.1.11", "0.1.12")).toThrow(/找不到 version/);
  });

  it("readCargoPackageVersion 取的是 [package] 段而非依赖段", () => {
    expect(readCargoPackageVersion(cargoToml)).toBe("0.1.11");
    const depFirst = ["[dependencies.foo]", 'version = "9.9.9"', "", "[package]", 'version = "0.1.11"', ""].join("\n");
    expect(readCargoPackageVersion(depFirst)).toBe("0.1.11");
  });
});

describe("replaceCargoLockVersion", () => {
  const cargoLock = [
    "# This file is automatically @generated by Cargo.",
    "version = 3",
    "",
    "[[package]]",
    'name = "async-stream"',
    'version = "0.1.11"',
    "",
    "[[package]]",
    'name = "provider-deck"',
    'version = "0.1.11"',
    "dependencies = [",
    ' "async-stream",',
    "]",
    "",
    "[[package]]",
    'name = "zerocopy"',
    'version = "0.1.11"',
    "",
  ].join("\n");

  it("只改 provider-deck 条目，同版本号的依赖条目不动", () => {
    const next = replaceCargoLockVersion(cargoLock, "provider-deck", "0.1.11", "0.1.12");
    const lines = next.split("\n");
    expect(lines[5]).toBe('version = "0.1.11"'); // async-stream
    expect(lines[9]).toBe('version = "0.1.12"'); // provider-deck
    expect(lines[16]).toBe('version = "0.1.11"'); // zerocopy
    // 锁文件顶部的 `version = 3` 是格式版本，不是包版本，绝不能被碰。
    expect(lines[1]).toBe("version = 3");
  });

  it("目标条目没有 version 键时抛错，不越界改到下一个条目", () => {
    const noVersion = [
      "[[package]]",
      'name = "provider-deck"',
      "dependencies = []",
      "",
      "[[package]]",
      'name = "other"',
      'version = "0.1.11"',
      "",
    ].join("\n");
    expect(() => replaceCargoLockVersion(noVersion, "provider-deck", "0.1.11", "0.1.12")).toThrow(
      /找不到 provider-deck 的 version/,
    );
  });

  it("条目不存在时抛错", () => {
    expect(() => replaceCargoLockVersion(cargoLock, "not-there", "0.1.11", "0.1.12")).toThrow(/找不到/);
  });

  it("readCargoLockVersion 读的是指定条目", () => {
    expect(readCargoLockVersion(cargoLock, "provider-deck")).toBe("0.1.11");
    expect(readCargoLockVersion(cargoLock, "not-there")).toBe(null);
  });
});

describe("prependChangelogEntry", () => {
  const meta = { version: "0.1.12", date: "2026-08-13", commit: "abc1234", note: "" };

  it("空文件时创建带前言的日志", () => {
    const next = prependChangelogEntry("", meta);
    expect(next.startsWith("# Changelog")).toBe(true);
    expect(next).toContain("## 0.1.12 - 2026-08-13");
    expect(next).toContain("Git commit: abc1234");
  });

  it("没有 note 时留待填写占位，不编造摘要", () => {
    const next = prependChangelogEntry("", meta);
    expect(next).toContain("待补充");
  });

  it("给了 note 就用 note", () => {
    const next = prependChangelogEntry("", { ...meta, note: "- 新增版本自动升级逻辑。" });
    expect(next).toContain("- 新增版本自动升级逻辑。");
    expect(next).not.toContain("待补充");
  });

  it("已有内容时新小节在最前，旧内容逐字保留", () => {
    const existing = ["# Changelog", "", "前言说明。", "", "## 0.1.11 - 2026-08-11", "", "- 旧版内容。", ""].join("\n");
    const next = prependChangelogEntry(existing, meta);
    const newIndex = next.indexOf("## 0.1.12");
    const oldIndex = next.indexOf("## 0.1.11");
    expect(newIndex).toBeGreaterThan(-1);
    expect(oldIndex).toBeGreaterThan(newIndex);
    // 前言仍在最上方，没被推到版本小节下面。
    expect(next.indexOf("前言说明。")).toBeLessThan(newIndex);
    expect(next).toContain("- 旧版内容。");
  });

  it("只有前言、还没有任何版本小节时追加到末尾", () => {
    const next = prependChangelogEntry("# Changelog\n\n前言说明。\n", meta);
    expect(next).toContain("前言说明。");
    expect(next).toContain("## 0.1.12 - 2026-08-13");
    expect(next.indexOf("前言说明。")).toBeLessThan(next.indexOf("## 0.1.12"));
  });
});

describe("parseArgs", () => {
  it("默认不 dry-run、无 note、无 out", () => {
    expect(parseArgs([])).toEqual({ dryRun: false, note: "", out: "" });
  });

  it("解析三个选项", () => {
    expect(parseArgs(["--dry-run", "--note", "摘要", "--out", "v.txt"])).toEqual({
      dryRun: true,
      note: "摘要",
      out: "v.txt",
    });
  });

  it("无法识别的参数直接抛错，避免拼错的选项被静默忽略", () => {
    expect(() => parseArgs(["--dryrun"])).toThrow(/无法识别的参数/);
  });
});

describe("localDate", () => {
  it("补零到 YYYY-MM-DD", () => {
    expect(localDate(new Date(2026, 0, 5))).toBe("2026-01-05");
    expect(localDate(new Date(2026, 11, 31))).toBe("2026-12-31");
  });
});

describe("输出与用例不含鉴权字段", () => {
  it("本测试文件涉及的文本里没有密钥形态字符串", () => {
    // 正向断言：确认扫描的确实是有内容的文本，避免下面的否定断言空转。
    const sample = [
      prependChangelogEntry("", { version: "0.1.12", date: "2026-08-13", commit: "abc1234", note: "" }),
      replaceJsonVersion('{\n  "version": "0.1.11"\n}\n', "0.1.11", "0.1.12"),
    ].join("\n");
    expect(sample).toContain("0.1.12");

    for (const needle of ["sk-", "AIza", "api_key", "apiKey", "Authorization", "Bearer"]) {
      expect(sample).not.toContain(needle);
    }
  });
});
